// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(spark_token_primitivesFFI)
import spark_token_primitivesFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_spark_token_primitives_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_spark_token_primitives_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct BroadcastBuildRequest {
    public var identityPublicKey: Data
    public var partialTokenTransactionBytes: Data
    public var ownerSignatures: [SignatureWithIndexInput]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identityPublicKey: Data, partialTokenTransactionBytes: Data, ownerSignatures: [SignatureWithIndexInput]) {
        self.identityPublicKey = identityPublicKey
        self.partialTokenTransactionBytes = partialTokenTransactionBytes
        self.ownerSignatures = ownerSignatures
    }
}



extension BroadcastBuildRequest: Equatable, Hashable {
    public static func ==(lhs: BroadcastBuildRequest, rhs: BroadcastBuildRequest) -> Bool {
        if lhs.identityPublicKey != rhs.identityPublicKey {
            return false
        }
        if lhs.partialTokenTransactionBytes != rhs.partialTokenTransactionBytes {
            return false
        }
        if lhs.ownerSignatures != rhs.ownerSignatures {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identityPublicKey)
        hasher.combine(partialTokenTransactionBytes)
        hasher.combine(ownerSignatures)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBroadcastBuildRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BroadcastBuildRequest {
        return
            try BroadcastBuildRequest(
                identityPublicKey: FfiConverterData.read(from: &buf), 
                partialTokenTransactionBytes: FfiConverterData.read(from: &buf), 
                ownerSignatures: FfiConverterSequenceTypeSignatureWithIndexInput.read(from: &buf)
        )
    }

    public static func write(_ value: BroadcastBuildRequest, into buf: inout [UInt8]) {
        FfiConverterData.write(value.identityPublicKey, into: &buf)
        FfiConverterData.write(value.partialTokenTransactionBytes, into: &buf)
        FfiConverterSequenceTypeSignatureWithIndexInput.write(value.ownerSignatures, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBroadcastBuildRequest_lift(_ buf: RustBuffer) throws -> BroadcastBuildRequest {
    return try FfiConverterTypeBroadcastBuildRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBroadcastBuildRequest_lower(_ value: BroadcastBuildRequest) -> RustBuffer {
    return FfiConverterTypeBroadcastBuildRequest.lower(value)
}


public struct FinalizeTokenInvoiceRequest {
    public var receiverIdentityPublicKey: Data
    public var network: UInt32
    public var sparkInvoiceFieldsBytes: Data
    public var signature: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(receiverIdentityPublicKey: Data, network: UInt32, sparkInvoiceFieldsBytes: Data, signature: Data?) {
        self.receiverIdentityPublicKey = receiverIdentityPublicKey
        self.network = network
        self.sparkInvoiceFieldsBytes = sparkInvoiceFieldsBytes
        self.signature = signature
    }
}



extension FinalizeTokenInvoiceRequest: Equatable, Hashable {
    public static func ==(lhs: FinalizeTokenInvoiceRequest, rhs: FinalizeTokenInvoiceRequest) -> Bool {
        if lhs.receiverIdentityPublicKey != rhs.receiverIdentityPublicKey {
            return false
        }
        if lhs.network != rhs.network {
            return false
        }
        if lhs.sparkInvoiceFieldsBytes != rhs.sparkInvoiceFieldsBytes {
            return false
        }
        if lhs.signature != rhs.signature {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(receiverIdentityPublicKey)
        hasher.combine(network)
        hasher.combine(sparkInvoiceFieldsBytes)
        hasher.combine(signature)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFinalizeTokenInvoiceRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FinalizeTokenInvoiceRequest {
        return
            try FinalizeTokenInvoiceRequest(
                receiverIdentityPublicKey: FfiConverterData.read(from: &buf), 
                network: FfiConverterUInt32.read(from: &buf), 
                sparkInvoiceFieldsBytes: FfiConverterData.read(from: &buf), 
                signature: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: FinalizeTokenInvoiceRequest, into buf: inout [UInt8]) {
        FfiConverterData.write(value.receiverIdentityPublicKey, into: &buf)
        FfiConverterUInt32.write(value.network, into: &buf)
        FfiConverterData.write(value.sparkInvoiceFieldsBytes, into: &buf)
        FfiConverterOptionData.write(value.signature, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFinalizeTokenInvoiceRequest_lift(_ buf: RustBuffer) throws -> FinalizeTokenInvoiceRequest {
    return try FfiConverterTypeFinalizeTokenInvoiceRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFinalizeTokenInvoiceRequest_lower(_ value: FinalizeTokenInvoiceRequest) -> RustBuffer {
    return FfiConverterTypeFinalizeTokenInvoiceRequest.lower(value)
}


public struct PartialTransferBuildResult {
    public var partialTokenTransactionBytes: Data
    public var partialTokenTransactionHash: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(partialTokenTransactionBytes: Data, partialTokenTransactionHash: Data) {
        self.partialTokenTransactionBytes = partialTokenTransactionBytes
        self.partialTokenTransactionHash = partialTokenTransactionHash
    }
}



extension PartialTransferBuildResult: Equatable, Hashable {
    public static func ==(lhs: PartialTransferBuildResult, rhs: PartialTransferBuildResult) -> Bool {
        if lhs.partialTokenTransactionBytes != rhs.partialTokenTransactionBytes {
            return false
        }
        if lhs.partialTokenTransactionHash != rhs.partialTokenTransactionHash {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(partialTokenTransactionBytes)
        hasher.combine(partialTokenTransactionHash)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePartialTransferBuildResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PartialTransferBuildResult {
        return
            try PartialTransferBuildResult(
                partialTokenTransactionBytes: FfiConverterData.read(from: &buf), 
                partialTokenTransactionHash: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: PartialTransferBuildResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.partialTokenTransactionBytes, into: &buf)
        FfiConverterData.write(value.partialTokenTransactionHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePartialTransferBuildResult_lift(_ buf: RustBuffer) throws -> PartialTransferBuildResult {
    return try FfiConverterTypePartialTransferBuildResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePartialTransferBuildResult_lower(_ value: PartialTransferBuildResult) -> RustBuffer {
    return FfiConverterTypePartialTransferBuildResult.lower(value)
}


public struct PrepareTokenInvoiceRequest {
    public var receiverIdentityPublicKey: Data
    public var network: UInt32
    public var tokenIdentifier: Data?
    public var tokenAmount: Data?
    public var memo: String?
    public var senderSparkAddress: String?
    public var expiryTimeUnixMillis: UInt64?
    public var invoiceId: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(receiverIdentityPublicKey: Data, network: UInt32, tokenIdentifier: Data?, tokenAmount: Data?, memo: String?, senderSparkAddress: String?, expiryTimeUnixMillis: UInt64?, invoiceId: Data?) {
        self.receiverIdentityPublicKey = receiverIdentityPublicKey
        self.network = network
        self.tokenIdentifier = tokenIdentifier
        self.tokenAmount = tokenAmount
        self.memo = memo
        self.senderSparkAddress = senderSparkAddress
        self.expiryTimeUnixMillis = expiryTimeUnixMillis
        self.invoiceId = invoiceId
    }
}



extension PrepareTokenInvoiceRequest: Equatable, Hashable {
    public static func ==(lhs: PrepareTokenInvoiceRequest, rhs: PrepareTokenInvoiceRequest) -> Bool {
        if lhs.receiverIdentityPublicKey != rhs.receiverIdentityPublicKey {
            return false
        }
        if lhs.network != rhs.network {
            return false
        }
        if lhs.tokenIdentifier != rhs.tokenIdentifier {
            return false
        }
        if lhs.tokenAmount != rhs.tokenAmount {
            return false
        }
        if lhs.memo != rhs.memo {
            return false
        }
        if lhs.senderSparkAddress != rhs.senderSparkAddress {
            return false
        }
        if lhs.expiryTimeUnixMillis != rhs.expiryTimeUnixMillis {
            return false
        }
        if lhs.invoiceId != rhs.invoiceId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(receiverIdentityPublicKey)
        hasher.combine(network)
        hasher.combine(tokenIdentifier)
        hasher.combine(tokenAmount)
        hasher.combine(memo)
        hasher.combine(senderSparkAddress)
        hasher.combine(expiryTimeUnixMillis)
        hasher.combine(invoiceId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrepareTokenInvoiceRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrepareTokenInvoiceRequest {
        return
            try PrepareTokenInvoiceRequest(
                receiverIdentityPublicKey: FfiConverterData.read(from: &buf), 
                network: FfiConverterUInt32.read(from: &buf), 
                tokenIdentifier: FfiConverterOptionData.read(from: &buf), 
                tokenAmount: FfiConverterOptionData.read(from: &buf), 
                memo: FfiConverterOptionString.read(from: &buf), 
                senderSparkAddress: FfiConverterOptionString.read(from: &buf), 
                expiryTimeUnixMillis: FfiConverterOptionUInt64.read(from: &buf), 
                invoiceId: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: PrepareTokenInvoiceRequest, into buf: inout [UInt8]) {
        FfiConverterData.write(value.receiverIdentityPublicKey, into: &buf)
        FfiConverterUInt32.write(value.network, into: &buf)
        FfiConverterOptionData.write(value.tokenIdentifier, into: &buf)
        FfiConverterOptionData.write(value.tokenAmount, into: &buf)
        FfiConverterOptionString.write(value.memo, into: &buf)
        FfiConverterOptionString.write(value.senderSparkAddress, into: &buf)
        FfiConverterOptionUInt64.write(value.expiryTimeUnixMillis, into: &buf)
        FfiConverterOptionData.write(value.invoiceId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrepareTokenInvoiceRequest_lift(_ buf: RustBuffer) throws -> PrepareTokenInvoiceRequest {
    return try FfiConverterTypePrepareTokenInvoiceRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrepareTokenInvoiceRequest_lower(_ value: PrepareTokenInvoiceRequest) -> RustBuffer {
    return FfiConverterTypePrepareTokenInvoiceRequest.lower(value)
}


public struct PreparedTokenInvoice {
    public var sparkInvoiceFieldsBytes: Data
    public var sparkInvoiceHash: Data
    public var unsignedSparkAddress: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sparkInvoiceFieldsBytes: Data, sparkInvoiceHash: Data, unsignedSparkAddress: String) {
        self.sparkInvoiceFieldsBytes = sparkInvoiceFieldsBytes
        self.sparkInvoiceHash = sparkInvoiceHash
        self.unsignedSparkAddress = unsignedSparkAddress
    }
}



extension PreparedTokenInvoice: Equatable, Hashable {
    public static func ==(lhs: PreparedTokenInvoice, rhs: PreparedTokenInvoice) -> Bool {
        if lhs.sparkInvoiceFieldsBytes != rhs.sparkInvoiceFieldsBytes {
            return false
        }
        if lhs.sparkInvoiceHash != rhs.sparkInvoiceHash {
            return false
        }
        if lhs.unsignedSparkAddress != rhs.unsignedSparkAddress {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sparkInvoiceFieldsBytes)
        hasher.combine(sparkInvoiceHash)
        hasher.combine(unsignedSparkAddress)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreparedTokenInvoice: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreparedTokenInvoice {
        return
            try PreparedTokenInvoice(
                sparkInvoiceFieldsBytes: FfiConverterData.read(from: &buf), 
                sparkInvoiceHash: FfiConverterData.read(from: &buf), 
                unsignedSparkAddress: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PreparedTokenInvoice, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sparkInvoiceFieldsBytes, into: &buf)
        FfiConverterData.write(value.sparkInvoiceHash, into: &buf)
        FfiConverterString.write(value.unsignedSparkAddress, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedTokenInvoice_lift(_ buf: RustBuffer) throws -> PreparedTokenInvoice {
    return try FfiConverterTypePreparedTokenInvoice.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedTokenInvoice_lower(_ value: PreparedTokenInvoice) -> RustBuffer {
    return FfiConverterTypePreparedTokenInvoice.lower(value)
}


public struct ReceiverTokenOutput {
    public var receiverSparkAddress: String
    public var tokenIdentifier: Data?
    public var tokenAmount: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(receiverSparkAddress: String, tokenIdentifier: Data?, tokenAmount: Data?) {
        self.receiverSparkAddress = receiverSparkAddress
        self.tokenIdentifier = tokenIdentifier
        self.tokenAmount = tokenAmount
    }
}



extension ReceiverTokenOutput: Equatable, Hashable {
    public static func ==(lhs: ReceiverTokenOutput, rhs: ReceiverTokenOutput) -> Bool {
        if lhs.receiverSparkAddress != rhs.receiverSparkAddress {
            return false
        }
        if lhs.tokenIdentifier != rhs.tokenIdentifier {
            return false
        }
        if lhs.tokenAmount != rhs.tokenAmount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(receiverSparkAddress)
        hasher.combine(tokenIdentifier)
        hasher.combine(tokenAmount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReceiverTokenOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReceiverTokenOutput {
        return
            try ReceiverTokenOutput(
                receiverSparkAddress: FfiConverterString.read(from: &buf), 
                tokenIdentifier: FfiConverterOptionData.read(from: &buf), 
                tokenAmount: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: ReceiverTokenOutput, into buf: inout [UInt8]) {
        FfiConverterString.write(value.receiverSparkAddress, into: &buf)
        FfiConverterOptionData.write(value.tokenIdentifier, into: &buf)
        FfiConverterOptionData.write(value.tokenAmount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReceiverTokenOutput_lift(_ buf: RustBuffer) throws -> ReceiverTokenOutput {
    return try FfiConverterTypeReceiverTokenOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReceiverTokenOutput_lower(_ value: ReceiverTokenOutput) -> RustBuffer {
    return FfiConverterTypeReceiverTokenOutput.lower(value)
}


public struct SelectedTokenOutput {
    public var previousTransactionHash: Data
    public var previousTransactionVout: UInt32
    public var ownerPublicKey: Data
    public var tokenIdentifier: Data
    public var tokenAmount: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(previousTransactionHash: Data, previousTransactionVout: UInt32, ownerPublicKey: Data, tokenIdentifier: Data, tokenAmount: Data) {
        self.previousTransactionHash = previousTransactionHash
        self.previousTransactionVout = previousTransactionVout
        self.ownerPublicKey = ownerPublicKey
        self.tokenIdentifier = tokenIdentifier
        self.tokenAmount = tokenAmount
    }
}



extension SelectedTokenOutput: Equatable, Hashable {
    public static func ==(lhs: SelectedTokenOutput, rhs: SelectedTokenOutput) -> Bool {
        if lhs.previousTransactionHash != rhs.previousTransactionHash {
            return false
        }
        if lhs.previousTransactionVout != rhs.previousTransactionVout {
            return false
        }
        if lhs.ownerPublicKey != rhs.ownerPublicKey {
            return false
        }
        if lhs.tokenIdentifier != rhs.tokenIdentifier {
            return false
        }
        if lhs.tokenAmount != rhs.tokenAmount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(previousTransactionHash)
        hasher.combine(previousTransactionVout)
        hasher.combine(ownerPublicKey)
        hasher.combine(tokenIdentifier)
        hasher.combine(tokenAmount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSelectedTokenOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SelectedTokenOutput {
        return
            try SelectedTokenOutput(
                previousTransactionHash: FfiConverterData.read(from: &buf), 
                previousTransactionVout: FfiConverterUInt32.read(from: &buf), 
                ownerPublicKey: FfiConverterData.read(from: &buf), 
                tokenIdentifier: FfiConverterData.read(from: &buf), 
                tokenAmount: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SelectedTokenOutput, into buf: inout [UInt8]) {
        FfiConverterData.write(value.previousTransactionHash, into: &buf)
        FfiConverterUInt32.write(value.previousTransactionVout, into: &buf)
        FfiConverterData.write(value.ownerPublicKey, into: &buf)
        FfiConverterData.write(value.tokenIdentifier, into: &buf)
        FfiConverterData.write(value.tokenAmount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelectedTokenOutput_lift(_ buf: RustBuffer) throws -> SelectedTokenOutput {
    return try FfiConverterTypeSelectedTokenOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelectedTokenOutput_lower(_ value: SelectedTokenOutput) -> RustBuffer {
    return FfiConverterTypeSelectedTokenOutput.lower(value)
}


public struct SignatureWithIndexInput {
    public var inputIndex: UInt32
    public var publicKey: Data
    public var signature: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(inputIndex: UInt32, publicKey: Data, signature: Data) {
        self.inputIndex = inputIndex
        self.publicKey = publicKey
        self.signature = signature
    }
}



extension SignatureWithIndexInput: Equatable, Hashable {
    public static func ==(lhs: SignatureWithIndexInput, rhs: SignatureWithIndexInput) -> Bool {
        if lhs.inputIndex != rhs.inputIndex {
            return false
        }
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        if lhs.signature != rhs.signature {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(inputIndex)
        hasher.combine(publicKey)
        hasher.combine(signature)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignatureWithIndexInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignatureWithIndexInput {
        return
            try SignatureWithIndexInput(
                inputIndex: FfiConverterUInt32.read(from: &buf), 
                publicKey: FfiConverterData.read(from: &buf), 
                signature: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SignatureWithIndexInput, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.inputIndex, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
        FfiConverterData.write(value.signature, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureWithIndexInput_lift(_ buf: RustBuffer) throws -> SignatureWithIndexInput {
    return try FfiConverterTypeSignatureWithIndexInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureWithIndexInput_lower(_ value: SignatureWithIndexInput) -> RustBuffer {
    return FfiConverterTypeSignatureWithIndexInput.lower(value)
}


public struct TransferBuildRequest {
    public var identityPublicKey: Data
    public var selectedOutputs: [SelectedTokenOutput]
    public var receiverOutputs: [ReceiverTokenOutput]
    public var operatorIdentityPublicKeys: [Data]
    public var network: UInt32
    public var validityDurationSeconds: UInt64
    public var clientCreatedTimestampUnixMicros: Int64
    public var withdrawBondSats: UInt64
    public var withdrawRelativeBlockLocktime: UInt64
    public var executeBeforeUnixMicros: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identityPublicKey: Data, selectedOutputs: [SelectedTokenOutput], receiverOutputs: [ReceiverTokenOutput], operatorIdentityPublicKeys: [Data], network: UInt32, validityDurationSeconds: UInt64, clientCreatedTimestampUnixMicros: Int64, withdrawBondSats: UInt64, withdrawRelativeBlockLocktime: UInt64, executeBeforeUnixMicros: Int64?) {
        self.identityPublicKey = identityPublicKey
        self.selectedOutputs = selectedOutputs
        self.receiverOutputs = receiverOutputs
        self.operatorIdentityPublicKeys = operatorIdentityPublicKeys
        self.network = network
        self.validityDurationSeconds = validityDurationSeconds
        self.clientCreatedTimestampUnixMicros = clientCreatedTimestampUnixMicros
        self.withdrawBondSats = withdrawBondSats
        self.withdrawRelativeBlockLocktime = withdrawRelativeBlockLocktime
        self.executeBeforeUnixMicros = executeBeforeUnixMicros
    }
}



extension TransferBuildRequest: Equatable, Hashable {
    public static func ==(lhs: TransferBuildRequest, rhs: TransferBuildRequest) -> Bool {
        if lhs.identityPublicKey != rhs.identityPublicKey {
            return false
        }
        if lhs.selectedOutputs != rhs.selectedOutputs {
            return false
        }
        if lhs.receiverOutputs != rhs.receiverOutputs {
            return false
        }
        if lhs.operatorIdentityPublicKeys != rhs.operatorIdentityPublicKeys {
            return false
        }
        if lhs.network != rhs.network {
            return false
        }
        if lhs.validityDurationSeconds != rhs.validityDurationSeconds {
            return false
        }
        if lhs.clientCreatedTimestampUnixMicros != rhs.clientCreatedTimestampUnixMicros {
            return false
        }
        if lhs.withdrawBondSats != rhs.withdrawBondSats {
            return false
        }
        if lhs.withdrawRelativeBlockLocktime != rhs.withdrawRelativeBlockLocktime {
            return false
        }
        if lhs.executeBeforeUnixMicros != rhs.executeBeforeUnixMicros {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identityPublicKey)
        hasher.combine(selectedOutputs)
        hasher.combine(receiverOutputs)
        hasher.combine(operatorIdentityPublicKeys)
        hasher.combine(network)
        hasher.combine(validityDurationSeconds)
        hasher.combine(clientCreatedTimestampUnixMicros)
        hasher.combine(withdrawBondSats)
        hasher.combine(withdrawRelativeBlockLocktime)
        hasher.combine(executeBeforeUnixMicros)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransferBuildRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransferBuildRequest {
        return
            try TransferBuildRequest(
                identityPublicKey: FfiConverterData.read(from: &buf), 
                selectedOutputs: FfiConverterSequenceTypeSelectedTokenOutput.read(from: &buf), 
                receiverOutputs: FfiConverterSequenceTypeReceiverTokenOutput.read(from: &buf), 
                operatorIdentityPublicKeys: FfiConverterSequenceData.read(from: &buf), 
                network: FfiConverterUInt32.read(from: &buf), 
                validityDurationSeconds: FfiConverterUInt64.read(from: &buf), 
                clientCreatedTimestampUnixMicros: FfiConverterInt64.read(from: &buf), 
                withdrawBondSats: FfiConverterUInt64.read(from: &buf), 
                withdrawRelativeBlockLocktime: FfiConverterUInt64.read(from: &buf), 
                executeBeforeUnixMicros: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TransferBuildRequest, into buf: inout [UInt8]) {
        FfiConverterData.write(value.identityPublicKey, into: &buf)
        FfiConverterSequenceTypeSelectedTokenOutput.write(value.selectedOutputs, into: &buf)
        FfiConverterSequenceTypeReceiverTokenOutput.write(value.receiverOutputs, into: &buf)
        FfiConverterSequenceData.write(value.operatorIdentityPublicKeys, into: &buf)
        FfiConverterUInt32.write(value.network, into: &buf)
        FfiConverterUInt64.write(value.validityDurationSeconds, into: &buf)
        FfiConverterInt64.write(value.clientCreatedTimestampUnixMicros, into: &buf)
        FfiConverterUInt64.write(value.withdrawBondSats, into: &buf)
        FfiConverterUInt64.write(value.withdrawRelativeBlockLocktime, into: &buf)
        FfiConverterOptionInt64.write(value.executeBeforeUnixMicros, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferBuildRequest_lift(_ buf: RustBuffer) throws -> TransferBuildRequest {
    return try FfiConverterTypeTransferBuildRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferBuildRequest_lower(_ value: TransferBuildRequest) -> RustBuffer {
    return FfiConverterTypeTransferBuildRequest.lower(value)
}


public enum SparkTokenPrimitivesError {

    
    
    case Spark(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSparkTokenPrimitivesError: FfiConverterRustBuffer {
    typealias SwiftType = SparkTokenPrimitivesError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SparkTokenPrimitivesError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Spark(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SparkTokenPrimitivesError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Spark(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


extension SparkTokenPrimitivesError: Equatable, Hashable {}

extension SparkTokenPrimitivesError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeReceiverTokenOutput: FfiConverterRustBuffer {
    typealias SwiftType = [ReceiverTokenOutput]

    public static func write(_ value: [ReceiverTokenOutput], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeReceiverTokenOutput.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ReceiverTokenOutput] {
        let len: Int32 = try readInt(&buf)
        var seq = [ReceiverTokenOutput]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeReceiverTokenOutput.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSelectedTokenOutput: FfiConverterRustBuffer {
    typealias SwiftType = [SelectedTokenOutput]

    public static func write(_ value: [SelectedTokenOutput], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSelectedTokenOutput.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SelectedTokenOutput] {
        let len: Int32 = try readInt(&buf)
        var seq = [SelectedTokenOutput]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSelectedTokenOutput.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSignatureWithIndexInput: FfiConverterRustBuffer {
    typealias SwiftType = [SignatureWithIndexInput]

    public static func write(_ value: [SignatureWithIndexInput], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSignatureWithIndexInput.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SignatureWithIndexInput] {
        let len: Int32 = try readInt(&buf)
        var seq = [SignatureWithIndexInput]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSignatureWithIndexInput.read(from: &buf))
        }
        return seq
    }
}
public func buildBroadcastTransactionRequest(request: BroadcastBuildRequest)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSparkTokenPrimitivesError.lift) {
    uniffi_spark_token_primitives_fn_func_build_broadcast_transaction_request(
        FfiConverterTypeBroadcastBuildRequest.lower(request),$0
    )
})
}
public func constructPartialTransferTransaction(request: TransferBuildRequest)throws  -> PartialTransferBuildResult {
    return try  FfiConverterTypePartialTransferBuildResult.lift(try rustCallWithError(FfiConverterTypeSparkTokenPrimitivesError.lift) {
    uniffi_spark_token_primitives_fn_func_construct_partial_transfer_transaction(
        FfiConverterTypeTransferBuildRequest.lower(request),$0
    )
})
}
public func finalizeTokenInvoice(request: FinalizeTokenInvoiceRequest)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSparkTokenPrimitivesError.lift) {
    uniffi_spark_token_primitives_fn_func_finalize_token_invoice(
        FfiConverterTypeFinalizeTokenInvoiceRequest.lower(request),$0
    )
})
}
public func hashPartialTokenTransaction(partialTokenTransactionBytes: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSparkTokenPrimitivesError.lift) {
    uniffi_spark_token_primitives_fn_func_hash_partial_token_transaction(
        FfiConverterData.lower(partialTokenTransactionBytes),$0
    )
})
}
public func prepareTokenInvoice(request: PrepareTokenInvoiceRequest)throws  -> PreparedTokenInvoice {
    return try  FfiConverterTypePreparedTokenInvoice.lift(try rustCallWithError(FfiConverterTypeSparkTokenPrimitivesError.lift) {
    uniffi_spark_token_primitives_fn_func_prepare_token_invoice(
        FfiConverterTypePrepareTokenInvoiceRequest.lower(request),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_spark_token_primitives_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_spark_token_primitives_checksum_func_build_broadcast_transaction_request() != 6918) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spark_token_primitives_checksum_func_construct_partial_transfer_transaction() != 48271) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spark_token_primitives_checksum_func_finalize_token_invoice() != 61372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spark_token_primitives_checksum_func_hash_partial_token_transaction() != 26626) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_spark_token_primitives_checksum_func_prepare_token_invoice() != 61985) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all