#!/usr/bin/env python3
"""Run a local Blockstream ChillDKG demo ceremony and emit JSON.

This script intentionally lives outside the Spark SDK package. It vendors and
uses BlockstreamResearch/bip-frost-dkg's Python reference implementation under
`dkg/vendor`, then writes a compact demo artifact that the Spark compatibility
smoke test can consume.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from secrets import token_bytes
import sys
from typing import Any

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "vendor"))

from chilldkg_ref.chilldkg import (  # noqa: E402
    DKGOutput,
    RecoveryData,
    SessionParams,
    coordinator_finalize,
    coordinator_step1,
    hostpubkey_gen,
    params_id,
    participant_finalize,
    participant_step1,
    participant_step2,
    recover,
)


def bytes_hex(value: bytes | None) -> str | None:
    if value is None:
        return None
    return value.hex()


def output_json(output: DKGOutput) -> dict[str, Any]:
    return {
        "secshareHex": bytes_hex(output.secshare),
        "thresholdPubkeyHex": output.threshold_pubkey.hex(),
        "pubshareHexes": [pubshare.hex() for pubshare in output.pubshares],
    }


def run_chilldkg(threshold: int, participants: int) -> dict[str, Any]:
    host_secrets = [token_bytes(32) for _ in range(participants)]
    host_public_keys = [hostpubkey_gen(secret) for secret in host_secrets]
    params = SessionParams(host_public_keys, threshold)

    participant_states_1 = []
    participant_messages_1 = []
    for host_secret in host_secrets:
        state_1, message_1 = participant_step1(
            host_secret,
            params,
            token_bytes(32),
        )
        participant_states_1.append(state_1)
        participant_messages_1.append(message_1)

    coordinator_state, coordinator_message_1 = coordinator_step1(
        participant_messages_1,
        params,
    )

    participant_states_2 = []
    participant_messages_2 = []
    for host_secret, state_1 in zip(host_secrets, participant_states_1):
        state_2, message_2 = participant_step2(
            host_secret,
            state_1,
            coordinator_message_1,
            token_bytes(32),
        )
        participant_states_2.append(state_2)
        participant_messages_2.append(message_2)

    coordinator_message_2, coordinator_output, recovery_data = coordinator_finalize(
        coordinator_state,
        participant_messages_2,
    )

    participant_outputs: list[DKGOutput] = []
    participant_recovery_data: list[RecoveryData] = []
    for state_2 in participant_states_2:
        output, participant_recovery = participant_finalize(
            state_2,
            coordinator_message_2,
        )
        participant_outputs.append(output)
        participant_recovery_data.append(participant_recovery)

    if any(output.threshold_pubkey != coordinator_output.threshold_pubkey for output in participant_outputs):
        raise RuntimeError("participants disagreed on threshold public key")
    if len({bytes(recovery_data), *[bytes(data) for data in participant_recovery_data]}) != 1:
        raise RuntimeError("participants disagreed on recovery data")

    recovered_outputs = []
    for host_secret in host_secrets:
        recovered, recovered_params = recover(host_secret, recovery_data)
        if recovered_params != params:
            raise RuntimeError("recovered params differ from original params")
        recovered_outputs.append(recovered)

    return {
        "implementation": "BlockstreamResearch/bip-frost-dkg python reference",
        "protocol": "ChillDKG",
        "curve": "secp256k1",
        "threshold": threshold,
        "participants": participants,
        "participantIndexBase": 1,
        "paramsIdHex": params_id(params).hex(),
        "hostSecretHexes": [secret.hex() for secret in host_secrets],
        "hostPubkeyHexes": [pubkey.hex() for pubkey in host_public_keys],
        "coordinator": output_json(coordinator_output),
        "participantsOutput": [
            {
                "index": index + 1,
                **output_json(output),
            }
            for index, output in enumerate(participant_outputs)
        ],
        "recoveredParticipantsOutput": [
            {
                "index": index + 1,
                **output_json(output),
            }
            for index, output in enumerate(recovered_outputs)
        ],
        "recoveryDataHex": bytes(recovery_data).hex(),
        "notes": [
            "This artifact contains demo host secrets and secret shares.",
            "Do not commit files from dkg/state.",
            "No composite private key is generated by ChillDKG.",
        ],
    }


def write_split_keyshare_files(artifact: dict[str, Any], output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    group = {
        "kind": "spark-frost-chilldkg-group",
        "version": 1,
        "implementation": artifact["implementation"],
        "protocol": artifact["protocol"],
        "curve": artifact["curve"],
        "threshold": artifact["threshold"],
        "participants": artifact["participants"],
        "participantIndexBase": artifact["participantIndexBase"],
        "paramsIdHex": artifact["paramsIdHex"],
        "hostPubkeyHexes": artifact["hostPubkeyHexes"],
        "coordinator": artifact["coordinator"],
        "recoveryDataHex": artifact["recoveryDataHex"],
        "notes": [
            "Public coordinator metadata for the spark-frost DKG demo.",
            "This file is safe to share with the signing coordinator.",
            "Participant secret shares live in participant-*-share.txt files.",
        ],
    }
    (output_dir / "group.txt").write_text(
        json.dumps(group, indent=2) + "\n",
        encoding="utf8",
    )

    for participant in artifact["participantsOutput"]:
        share = {
            "kind": "spark-frost-chilldkg-keyshare",
            "version": 1,
            "implementation": artifact["implementation"],
            "protocol": artifact["protocol"],
            "curve": artifact["curve"],
            "threshold": artifact["threshold"],
            "participants": artifact["participants"],
            "participantIndexBase": artifact["participantIndexBase"],
            "paramsIdHex": artifact["paramsIdHex"],
            "index": participant["index"],
            "secshareHex": participant["secshareHex"],
            "thresholdPubkeyHex": artifact["coordinator"]["thresholdPubkeyHex"],
            "pubshareHexes": participant["pubshareHexes"],
            "notes": [
                "Demo participant key share. Keep this file private.",
                "A real wallet would store this on a separate signer device.",
            ],
        }
        filename = f"participant-{participant['index']}-share.txt"
        (output_dir / filename).write_text(
            json.dumps(share, indent=2) + "\n",
            encoding="utf8",
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Run a local ChillDKG demo")
    parser.add_argument("--threshold", "-t", type=int, default=2)
    parser.add_argument("--participants", "-n", type=int, default=3)
    parser.add_argument(
        "--output",
        "-o",
        default="state/chilldkg-2of3.json",
        help="Output JSON path, relative to dkg/ by default",
    )
    parser.add_argument(
        "--output-dir",
        help="Directory for split group/keyshare text files, relative to dkg/ by default",
    )
    args = parser.parse_args()

    artifact = run_chilldkg(args.threshold, args.participants)
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = ROOT / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(artifact, indent=2) + "\n", encoding="utf8")

    print(f"wrote {output_path}")
    if args.output_dir:
        output_dir = Path(args.output_dir)
        if not output_dir.is_absolute():
            output_dir = ROOT / output_dir
        write_split_keyshare_files(artifact, output_dir)
        print(f"wrote split keyshare files in {output_dir}")
    print(f"threshold public key: {artifact['coordinator']['thresholdPubkeyHex']}")
    print(f"params id: {artifact['paramsIdHex']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
